local completion = require "cc.completion"

local R_terminal = require "lib.cc.terminal"

local config = require "lib.config"
local R_string = require "lib.string"
local R_table = require "lib.table"
local trace = require "lib.trace"

trace.scall(
function()

--- @type string
local directory = fs.getDir(shell.getRunningProgram())
if directory == "" then directory = "." end

--- @return string[]
local function __get_all_programs()
    local programs = fs.list(directory) --[[@as string[]=]]

    R_table.remove_values(programs, "installer.lua", "launcher.lua", "lib", "logs", config.DIRECTORY)
    R_table.remove_values_where(programs, function(file) return not R_string.ends_with(file, ".lua") end)
    R_table.transform_values(programs, function(file) return file:sub(1, -5) end)

    return programs
end

local programs = __get_all_programs()

if #programs == 0 then
    print("No programs were installed, aborting")
    return
end

local build = false
--- @type string[]
local order = {}

-- Program choice loop
while not build do
    R_terminal.reset_terminal()

    if #order == 0 then
        print("Order:")
        print("  <none>")
    else
        print("Order:")
        for _, file in ipairs(order) do
            print(string.format("  %s", file))
        end
    end

    print()
    print("Enter program name, 'clear' to reset or 'build' to finish:")
    write("? ")

    local choice = read(nil, nil, function(text) return completion.choice(text, programs) end)

    if choice == "clear" then
        order = {}
        programs = __get_all_programs()
    elseif choice == "build" then
        if #order == 0 then
            print("No programs were chosen, aborting")
            return
        end

        build = true
    elseif R_table.contains(programs, choice) then
        table.insert(order, choice)
        R_table.remove_values(programs, choice)
    end
end

term.clear()
print("Chosen order:")
for _, file in ipairs(order) do
    print(string.format("  %s", file))
end

print()
print("Building startup...")

if fs.exists("startup.lua") then
    print("A startup.lua already exists, backing up to startup.lua.bak")
    if fs.exists("startup.lua.bak") then fs.delete("startup.lua.bak") end
    fs.move("startup.lua", "startup.lua.bak")
end

local startup = fs.open("startup.lua", "w")
startup.writeLine("-- This file was generated by startup_builder.lua")
startup.writeLine("-- To modify the startup sequence, run startup_builder.lua again and follow the prompts")
startup.writeLine("local directory = fs.getDir(shell.getRunningProgram())")
startup.writeLine("if directory == \"\" then directory = \".\" end")
startup.writeLine("")
startup.writeLine("local pid")
for _, file in ipairs(order) do
    startup.writeLine("")
    startup.writeLine(string.format("pid = shell.openTab(directory .. \"/%s.lua\")", file))
    startup.writeLine(string.format("multishell.setTitle(pid, \"%s\")", file))
end
startup.writeLine("multishell.setFocus(pid)")
startup.close()

print("Done!")
print("Reboot to run the new startup sequence.")

end
)